In [10]:
#Задание 1
"""Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))."""

import numpy as np
N = int(input("Введите количество элементов массива: "))

numpy_array = np.arange(N)
numpy_array[::-1]

Введите количество элементов массива: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
#Задание 2
"""Создайте диагональную матрицу с элементами от N до 0. 
Посчитайте сумму ее значений на диагонали."""

import numpy as np
N = int(input("Введите верхнюю границу диапазона элементов диагональной матрицы: "))
numpy_array_for_diag = np.arange(N) #создаем массив, который станет диагональю диагональной матрицы
matrix_diag = np.diag((numpy_array_for_diag[::-1]))
print(f'{matrix_diag}\nCумма диагональных элементов матрицы: {np.trace(matrix_diag)}')



Введите верхнюю границу диапазона элементов диагональной матрицы: 4
[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]]
Cумма диагональных элементов матрицы: 6


In [26]:
#Задание 3
"""
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""
import numpy as np


a = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4] ]) #коэффициенты переменных
b = np.array([4, 12, -3]) #значения уравнений

from numpy import linalg

linalg.solve(a,b)


array([ 0.46666667,  3.84444444, -5.55555556])

In [68]:
#Задание 4
"""Имеется матрица покупок users_stats в интернет-магазине. 
Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем:
На сайт заходит очередной посетитель next_user_stats.
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями 
из массива user_stats
"""
import numpy as np
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

i = 0

cosine_list = []

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )


for users_stats[i] in users_stats: # проходим по строкам матрицы
    cosine_list.append(cosine( users_stats[i], next_user_stats )) #формируем список косинусов
    i += 1
    
print(f'Обнаружено максимальное сходство с пользователем, данные которого: \
{users_stats[cosine_list.index(max(cosine_list))]}\nЗначение косинуса: {max(cosine_list)}')  

#по индексу максимального косинуса (угол в этом случае->0) находим соотвествующего пользователя
#предполагается, что такой пользователь один
    
   



Обнаружено максимальное сходство с пользователем, данные которого: [0 1 1 0 0 0]
Значение косинуса: 0.9486832980505138


In [96]:
#Задание 4 при условии нескольких схожих пользователей

import numpy as np
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [0, 1, 1, 0, 0, 0],#
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

i = 0

cosine_list = []

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )


for users_stats[i] in users_stats: # проходим по строкам матрицы
    cosine_list.append(cosine( users_stats[i], next_user_stats )) #формируем список косинусов
    i += 1

index_list = []

for index, max_cos in enumerate(cosine_list):
    if max_cos == max(cosine_list):
        index_list.append(index)
print(index_list)
        #
if len(index_list) > 1:
        for j in index_list:
            
            print(f'Обнаружено максимальное сходство с пользователем, данные которого: \
{users_stats[j]}\nЗначение косинуса: {max(cosine_list)}') 
            
        
        
    
 
    

[6, 7]
Обнаружено максимальное сходство с пользователем, данные которого: [0 1 1 0 0 0]
Значение косинуса: 0.9486832980505138
Обнаружено максимальное сходство с пользователем, данные которого: [0 1 1 0 0 0]
Значение косинуса: 0.9486832980505138
